name: Automatically update Flatcar docs on Branch Push
on:
  push:
    branches:
      - master

jobs:
  auto-flatcar-docs:
    name: Automatically update Flatcar docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: repository dispatch
        uses: peter-evans/repository-dispatch@v1.0.0
        with:
          token: ${{ secrets.FLATCAR_DOCS_ACCESS_TOKEN }}
          repository: kinvolk/docs.flatcar-linux.org
          event-type: docs-pull-request
